#!/usr/bin/env bash
# configure domain zone
ARR=('www' 'lb-01' 'web-01' 'web-02')
if [ $# -eq 2 ]
then
    SUBD="$2.$1"
    TEMP=$(dig "$SUBD" | grep -A1 'ANSWER SECTION:' | tail -1)
    A=$(echo "$TEMP" | awk '{ print $4 }')
    B=$(echo "$TEMP" | awk '{ print $5 }')
    echo "The subdomain $2 is a $A record and points to $B"
elif [ $# -eq 1 ]
then
    for i in "${ARR[@]}"
    do
        SUBD="$i.$1"
        TEMP=$(dig "$SUBD" | grep -A1 'ANSWER SECTION:' | tail -1)
        A=$(echo "$TEMP" | awk '{ print $4 }')
        B=$(echo "$TEMP" | awk '{ print $5 }')
        echo "The subdomain $i is a $A record and points to $B"
    done
fi
